# Generated by Django 5.0.7 on 2024-08-01 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=64)),
                ('pr_description', models.CharField(max_length=256)),
                ('pr_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.newscategory')),
            ],
        ),
    ]
