# Generated by Django 5.0.7 on 2024-08-02 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_newscategory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pr_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
