# Generated by Django 5.0.7 on 2024-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_news_pr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pr_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
