# Generated by Django 5.0.7 on 2024-08-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_news_pr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pr_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
