# Generated by Django 5.0.7 on 2024-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_news_pr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pr_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pr_img'),
        ),
    ]
